language: python
sudo: false
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-system-dev
      - libboost-filesystem-dev
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
script: pytest
