language: python
sudo: false
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - g++-4.8
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install codecov
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - pip install -e .
script:
  - pytest --cov
after_success:
  - codecov
