language: python
sudo: false
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - g++-4.8
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install .
script:
  - python setup.py test
notifications:
  slack: climate-models:kLhWus3hN9nXOI5VYYGORFEd
